apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "helm.fullname" . }}-config-maps
data:
  NEXT_PUBLIC_ENABLE_DOWNLOAD: "{{ .Values.configMaps.NEXT_PUBLIC_ENABLE_DOWNLOAD }}"
  REDIRECT_URI: "{{ .Values.configMaps.REDIRECT_URI }}"
  DOWNLOAD_SERVER_ADDRESS: "{{ .Values.configMaps.DOWNLOAD_SERVER_ADDRESS }}"
