apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ include "helm.fullname" . }}-secrets
data:
  ACCESS_KEY: {{ .Values.secrets.ACCESS_KEY | b64enc }}
  SECRET_KEY: {{ .Values.secrets.SECRET_KEY | b64enc }}
